import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * Installs dependencies for frontend or backend
 * @param directory The directory where to install dependencies
 * @param type 'frontend' or 'backend'
 */
export async function installDependencies(directory: string, type: 'frontend' | 'backend'): Promise<void> {
    const packageJsonPath = path.join(directory, 'package.json');
    
    // Check if package.json exists
    if (!fs.existsSync(packageJsonPath)) {
        if (type === 'backend') {
            // Backend should have package.json generated by AI
            throw new Error('Backend package.json not found. Backend generation may have failed.');
        } else {
            // Frontend might not have package.json yet, create one
            await initializeFrontendPackageJson(directory);
        }
    }

    try {
        console.log(`📦 Installing ${type} dependencies...`);
        
        // Show output channel for npm install
        const outputChannel = vscode.window.createOutputChannel(`BOB - ${type} Install`);
        outputChannel.show();
        outputChannel.appendLine(`Installing dependencies in: ${directory}`);
        
        // Run npm install
        const { stdout, stderr } = await execAsync('npm install', {
            cwd: directory,
            maxBuffer: 1024 * 1024 * 10 // 10MB buffer
        });
        
        if (stdout) {
            outputChannel.appendLine(stdout);
        }
        if (stderr) {
            outputChannel.appendLine(stderr);
        }
        
        outputChannel.appendLine(`✅ ${type} dependencies installed successfully!`);
        console.log(`✅ ${type} dependencies installed successfully!`);
        
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.error(`❌ Failed to install ${type} dependencies:`, errorMessage);
        throw new Error(`Failed to install ${type} dependencies: ${errorMessage}`);
    }
}

/**
 * Initializes a basic package.json for frontend with axios
 */
async function initializeFrontendPackageJson(directory: string): Promise<void> {
    const packageJson = {
        name: "frontend",
        version: "1.0.0",
        description: "Frontend application",
        dependencies: {
            "axios": "^1.6.0"
        }
    };
    
    const packageJsonPath = path.join(directory, 'package.json');
    
    // Check if package.json already exists
    if (fs.existsSync(packageJsonPath)) {
        // Read existing package.json and add axios if not present
        const existingPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        
        if (!existingPackageJson.dependencies) {
            existingPackageJson.dependencies = {};
        }
        
        if (!existingPackageJson.dependencies.axios) {
            existingPackageJson.dependencies.axios = "^1.6.0";
            fs.writeFileSync(packageJsonPath, JSON.stringify(existingPackageJson, null, 2), 'utf8');
            console.log('  📄 Updated package.json with axios dependency');
        }
    } else {
        // Create new package.json
        fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf8');
        console.log('  📄 Created package.json for frontend');
    }
}

/**
 * Checks if npm is available
 */
export async function checkNpmAvailable(): Promise<boolean> {
    try {
        await execAsync('npm --version');
        return true;
    } catch {
        return false;
    }
}

// Made with Bob
